
[mobSpawning]
	#0 fully disables it, 1 fully enables it, and an inbetween acts as a percentage chance for it to work (0.13 being 13%, for example.)
	"Baby Zombie Spawning" = 0.13

[mobHealth]
	#Allows you to set the amount of health mobs spawn with (if they're allowed to spawn at all.) I made it really low by default so as to make them less annoying to deal with if you do have to encounter them.
	"Baby Zombie Health" = 2.0
	"Phantom Health" = 6.0

[naturalSpawningDepth]
	#The specified mob will only naturally spawn below the specified y-level. This is so certain mobs are cave-exclusive by default.
	"Petriman Spawning Depth" = -10.0
	"Silverking Spawning Depth" = -10.0
	"Crawler Spawning Depth" = -10.0
	"Troll Spawning Depth" = -10.0
	"Vampire Spawning Depth" = -10.0
	"Intruder Spawning Depth" = 35.0
	"Cockatrice Spawning Depth" = 60.0

[mobReplacement]
	"Petriman Zombie Replacement" = 0.0
	"Silverking Spider Replacement" = 0.3
	"Crawler/Intruder Creeper Replacement" = 0.3
	"Vampire Skeleton Replacement" = 0.3
	"Troll Enderman Replacement" = 0.3
	"Cinder Blaze Replacement" = 0.0
	"Boar Pig Replacement" = 0.0
	"Bull Cow Replacement" = 0.0
	"Ram Sheep Replacement" = 0.0
	"Rooster Chicken Replacement" = 0.0
	"Tarantula Spider Replacement" = 0.3
	"Scorpion Spider Replacement" = 0.3
	"Gladilad Squid Replacement" = 0.0
	"Angler Common Fish Replacement" = 0.3
	"Random Enemy Expansion Zombie Replacement" = 0.3
	"Kelpie Angler Replacement" = 0.05
	"Illager Villager Replacement" = 0.0
	"Iron Golem Ravager Replacement" = 0.0

[mobReplacementDepth]
	"Petriman Zombie Replacement Depth" = 0.0
	"Silverking Spider Replacement Depth" = -10.0
	"Crawler/Intruder Creeper Replacement Depth" = -10.0
	"Vampire Skeleton Replacement Depth" = -10.0
	"Troll Enderman Replacement Depth" = -10.0

[hatWearerSpawning]
	#Some Zombies and Skeletons will spawn wearing certain special gear. edit the minecraft:is_meatury tag to choose what biomes these mobs spawn in.
	"Meat Head Wearer Spawning" = 0.01
	"Headbitten Wearer Spawning" = 0.01
	"Slimehead Wearer Spawning" = 0.01
	"Spiderlatch Wearer Spawning" = 0.01
	"Silverhead Wearer Spawning" = 0.01
	"Horsehead Wearer Spawning" = 0.01
	"Miniwither Wearer Spawning" = 0.01
	"Flutterfliers Wearer Spawning" = 0.01
	"Phantasm Wearer Spawning" = 0.01
	"Spectral Wearer Spawning" = 0.01
	"Brutish Garment Wearer Spawning" = 0.01
	"Bull Skull Wearer Spawning" = 0.01
	"Bane Mask Wearer Spawning" = 0.01
	"Gladling Wearer Spawning" = 0.01

[armorWearerSpawning]
	"Leather Wearer Spawning" = 0.01
	"Chainmail Wearer Spawning" = 0.01
	"Iron Wearer Spawning" = 0.01
	"Gold Wearer Spawning" = 0.007
	"Diamond Wearer Spawning" = 0.004
	"Netherite Wearer Spawning" = 0.001

[miscOptions]
	"Punching Ram Drops Wool Chance" = 0.0
	"Wandering Trader becomes Illusioner on-death Chance" = 0.1
	"Burning Undead mobs gain Speed III Chance" = 0.2
	"Mobs Sometimes Spawn With Varying Speed" = 0.2
	"Skeletons Switch Weapons Mid-Fight Chance" = 0.2

[effectSpawning]
	"Chance of Strength effect applied on mob-spawn" = 0.01
	"Chance of Speed effect applied on mob-spawn" = 0.01
	"Chance of Resistance effect applied on mob-spawn" = 0.01
	"Chance of Haste effect applied on mob-spawn" = 0.01
	"Chance of Fire Resistance effect applied on mob-spawn" = 0.01

