
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 876851
	#The name of the modpack
	modpackName = "Medieval MC [FORGE] 1.20.1"
	#The version of the modpack
	modpackVersion = "v26.5 HF"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

