
#Settings for Inventory HUD
[inventoryhud]
	#Inventory HUD mini mode
	invMini = false
	#Inventory HUD vertical mode
	invVert = false
	#Inventory HUD alpha
	#Range: 0 ~ 100
	invAlpha = 0
	#Toggle on by default
	byDefault = false
	#Animate recently picked up items
	animatedInv = false
	#Hide background if inventory is empty
	hideBackground = false
	#Show Inventory HUD when debug menu is open
	invWithDebug = true

#Settings for ArmorStatus HUD
[armorhud]
	#Is Armor Damage HUD enabled
	ArmorDamage = true
	#Hide if durability is above this (in percentage):
	#Range: 0 ~ 100
	armAbove = 100
	#Show/Hide armor
	showArmor = true
	#Show/Hide armor
	showMain = false
	#Show/Hide armor
	showOff = false
	#Show/Hide armor
	showArrows = false
	#Show/Hide armor
	showInv = false
	#Armor HUD durability view (PERCENTAGE, DAMAGE, DAMAGE LEFT)
	#Allowed Values: PERCENTAGE, DAMAGE, DAMAGE_LEFT, OFF
	armView = "PERCENTAGE"
	#Show item durability bar
	armBars = false
	#Move all items at once or each one
	moveAll = false
	#Show/Hide empty slot icon
	showEmpty = true
	#Show overall count of items in main/off hand
	showCount = false
	#ArmorHUD scale in persentage from 50 to 150
	#Range: 50 ~ 150
	armScale = 100
	#Show Armor HUD when debug menu is open
	armWithDebug = true
	#Show arrows count when no weapon in your hands
	showArrowsWithoutWeapon = true

#Settings for Potions HUD
[potionshud]
	#Is Potions HUD enabled
	Potions = true
	#Potion HUD alpha
	#Range: 0 ~ 100
	potAlpha = 100
	#Potion HUD gap
	#Range: -5 ~ 5
	potGap = 0
	#Potion HUD mini mode
	potMini = false
	#Potion HUD horizontal mode
	potHor = false
	#Full bar duration
	#Range: > 1
	barDuration = 300
	#Show hidden effects
	showHiddenEffects = false
	#Disable icons for effects in this list
	effectsBlackList = []
	#Show Potion HUD when debug menu is open
	potWithDebug = true
	#Show all levels of effects
	potionLevels = false

#DONT TOUCH THESE FIELDS!
[positions]
	#Inventory HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	invValign = "BOTTOM"
	#Inventory HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	invHalign = "MIDDLE"
	#Inventory HUD position (X)
	#Range: -9999 ~ 9999
	xPos = 0
	#Inventory HUD position (Y)
	#Range: -9999 ~ 9999
	yPos = 150
	#Armor HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	armValign = "BOTTOM"
	#Armor HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	armHalign = "MIDDLE"
	#Armor HUD position (X)
	#Range: -9999 ~ 9999
	xArmPos = 0
	#Armor HUD position (Y)
	#Range: -9999 ~ 9999
	yArmPos = 70
	#Potion HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	potValign = "TOP"
	#Potion HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	potHalign = "LEFT"
	#Potion HUD position (X)
	#Range: -9999 ~ 9999
	xPotionPos = 0
	#Potion HUD position (Y)
	#Range: -9999 ~ 9999
	yPotionPos = 135
	#Helmet position (X)
	#Range: -9999 ~ 9999
	helmPosX = 114
	#Helmet position (Y)
	#Range: -9999 ~ 9999
	helmPosY = 62
	#Chestplate position (X)
	#Range: -9999 ~ 9999
	chestPosX = 114
	#Chestplate position (Y)
	#Range: -9999 ~ 9999
	chestPosY = 40
	#Leggings position (X)
	#Range: -9999 ~ 9999
	legPosX = -111
	#Leggings position (Y)
	#Range: -9999 ~ 9999
	legPosY = 58
	#Boots position (X)
	#Range: -9999 ~ 9999
	bootPosX = -111
	#Boots position (Y)
	#Range: -9999 ~ 9999
	bootPosY = 36
	#MainHand position (X)
	#Range: -9999 ~ 9999
	mainPosX = 16
	#MainHand position (Y)
	#Range: -9999 ~ 9999
	mainPosY = 141
	#OffHand position (X)
	#Range: -9999 ~ 9999
	offPosX = 16
	#OffHand position (Y)
	#Range: -9999 ~ 9999
	offPosY = 131
	#Arrows position (X)
	#Range: -9999 ~ 9999
	arrPosX = 16
	#Arrows position (Y)
	#Range: -9999 ~ 9999
	arrPosY = 134
	#InvIcon position (X)
	#Range: -9999 ~ 9999
	invPosX = 16
	#InvIcon position (Y)
	#Range: -9999 ~ 9999
	invPosY = 136
	#Helmet horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	helmHal = "MIDDLE"
	#Helmet vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	helmVal = "BOTTOM"
	#Chestplate horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	chestHal = "MIDDLE"
	#Chestplate vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	chestVal = "BOTTOM"
	#Leggings horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	legHal = "MIDDLE"
	#Leggings vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	legVal = "BOTTOM"
	#Boots horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	bootHal = "MIDDLE"
	#Boots vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	bootVal = "BOTTOM"
	#MainHand horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	mainHal = "RIGHT"
	#MainHand vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	mainVal = "TOP"
	#OffHand horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	offHal = "RIGHT"
	#OffHand vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	offVal = "TOP"
	#Arrows horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	arrHal = "RIGHT"
	#Arrows vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	arrVal = "TOP"
	#InvIcon horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	invHal = "RIGHT"
	#InvIcon vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	invVal = "TOP"

#Notification settings
[notification]
	#Last notified mod version
	lastNotifiedVersion = "0.3.4-forge"
	#Notify more than once
	keepNotifying = true

